# Site settings
title: "jrjBlog - Joseph R. Jones"
email: jrj@jrj.org
description: > # this means to ignore newlines until "baseurl:"
  Security and Privacy, Technology and the Future… and other mental flotsam from the mind of Joseph R. Jones

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josephrjones.com" # the base hostname & protocol for your site
twitter_username: jrj
github_username:  jrjones

# Build settings
markdown: kramdown
paginate: 12

