# Site settings
title: JRJ's Test Jekyll Site
email: jrj@jrj.org
description: > # this means to ignore newlines until "baseurl:"
  This is a description that lives in the config.yml
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josephrjones.com" # the base hostname & protocol for your site
twitter_username: jrj
github_username:  jrjones

# Build settings
markdown: kramdown
